import Navbar from '@/components/shared/Navbar';
import './globals.css'
import Footer from '@/components/shared/Footer';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
   <html lang="en">
     <body>
       <Navbar />
       <div className='min-h-screen text-4xl'>{children}</div>
       <Footer />
     </body>
   </html>
 );
}
