import './globals.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
   <html lang="en">
     <body>
       <div className='min-h-screen text-4xl'>{children}</div>
     </body>
   </html>
 );
}
