import Sidebar from "@/components/shared/Sidebar";
import React from "react";
export const metadata = {
  title: "Next.js Dashboard Demo",
  description: "Generated by Next.js"
};

const DashboardLayout = ({ children }) => {
  return (
    <div>
      <Sidebar />
      {children}
    </div>
  );
};

export default DashboardLayout;
